[package]
name = "tokio-seqpacket"
version = "0.2.1"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Fizyr B.V. <info@fizyr.com>",
]
repository = "https://github.com/de-vri-es/tokio-seqpacket-rs"
readme = "README.md"
description = "unix seqpacket sockets for tokio"
keywords = ["seqpacket", "socket", "unix", "async", "tokio"]
categories = ["network-programming", "os::unix-apis"]

edition = "2018"

[dependencies]
futures = "0.3.7"
libc = "0.2.77"
socket2 = { version = "0.3.15", features = ["unix", "pair"] }
tokio = { version = "0.3.2", features = ["net"] }

[dev-dependencies]
assert2 = "0.3.3"
tokio = { version = "0.3.2", features = ["rt", "macros", "time"] }
tempfile = "3.1.0"

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", rev="c1539132110d3f8d20d22efb4b3f6a16fafd0e63" }

