[package]
name = "tokio-seqpacket"
version = "0.1.0"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Fizyr B.V. <info@fizyr.com>",
]
repository = "https://github.com/de-vri-es/tokio-seqpacket-rs"
description = "unix seqpacket sockets for tokio"
keywords = ["seqpacket", "socket", "unix", "async", "tokio"]
categories = ["network-programming", "os::unix-apis"]

edition = "2018"

[dependencies]
socket2 = { version = "0.3.15", features = ["unix", "pair"] }
tokio = { version = "0.2.22", features = ["io-driver", "uds"] }
mio = "0.6.0"
libc = "0.2.77"

[dev-dependencies]
assert2 = "0.3.3"
tokio = { version = "0.2.22", features = ["rt-core", "rt-util", "macros", "time"] }
tempfile = "3.1.0"
