[package]
name = "tokio-seqpacket"
version = "0.1.0"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Fizyr B.V. <info@fizyr.com>",
]
edition = "2018"

[dependencies]
socket2 = { version = "0.3.15", features = ["unix", "pair"] }
tokio = { version = "0.2.22", features = ["io-driver", "uds"] }
mio = "0.6.0"
libc = "0.2.77"
